app:
  env: dev

http:
  port: ":8080"

postgres:
  dsn: "host=localhost port=5432 user=app password=app dbname=appdb sslmode=disable TimeZone=UTC"

kafka:
  brokers:
    - localhost:19092
  topicUsersCreated: "users.created"

rabbit:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "user.notify"
  ttlms: 60000