app:
  env: "dev"

http:
  port: ":8080"

postgres:
  dsn: ""

kafka:
  brokers: []
  topicUsersCreated: "users.created"

rabbit:
  url: ""
  queue: "user.notify"
  ttlms: 60000

auth:
  domain: ""
  audience: ""